In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('/Users/janduplessis/code/janduplessis883/packages/project-noema/noema/data/fft_sheet_testing.csv')

In [4]:
data.head()

,,Respondent ID,Submitted at,"Overall, how was your experience of our service?",Please tell us&nbsp;why you feel this way?,Is there anything that would have made&nbsp;your experience better?,pcn,surgery,Untitled short answer field,Did you interact with our reception or administrative staff during your visit or in the last month?,"How satisfied were you with the helpfulness and efficiency of our reception/admin staff in handling your request (e.g., booking, prescription request, referrals)?","Please tell us the main reason for the score you gave above. What was the best part of your interaction, or what is the one thing we could do to make the process easier next time?"
0,mannual,upload,2024-01-01 10:51:00,Very good,Everyone kind and helpful,NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,NaN,NaN,NaN,NaN
1,mannual,upload,2024-01-01 15:20:00,Very good,Nothing. It was all great,NaN,Brompton-Health-PCN,Brompton-Health-PCN,NaN,NaN,NaN,NaN
2,NaN,NaN,2024-01-01 17:47:25,Very good,Knowledgable doctors,All Good,Brompton-Health-PCN,Earls-Court-Surgery,NaN,NaN,NaN,NaN
3,mannual,upload,2024-01-02 07:58:00,Good,"Denise was amazing, kind and helpful. The rece...",NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,NaN,NaN,NaN,NaN
4,mannual,upload,2024-01-02 10:44:00,Very good,Appointment,NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,NaN,NaN,NaN,NaN

In [7]:
data.columns = [
    "submission_id",
    "respondent-id",
    "time",
    "rating",
    "free_text",
    "do_better",
    "pcn",
    "surgery",
    "campaing_id",
    "logic",
    "campaign_rating",
    "campaign_freetext",
    ]

data["time"] = pd.to_datetime(data["time"], format="%Y-%m-%d %H:%M:%S")

data.sort_values(by="time", inplace=True)
data.drop(columns=['submission_id', 'respondent-id', 'rating', 'logic', 'campaign_rating'], inplace=True)

In [8]:
data.head()

,time,free_text,do_better,pcn,surgery,campaing_id,campaign_freetext
0,2024-01-01 10:51:00,Everyone kind and helpful,NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,NaN,NaN
1,2024-01-01 15:20:00,Nothing. It was all great,NaN,Brompton-Health-PCN,Brompton-Health-PCN,NaN,NaN
2,2024-01-01 17:47:25,Knowledgable doctors,All Good,Brompton-Health-PCN,Earls-Court-Surgery,NaN,NaN
3,2024-01-02 07:58:00,"Denise was amazing, kind and helpful. The rece...",NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,NaN,NaN
4,2024-01-02 10:44:00,Appointment,NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,NaN,NaN

In [9]:
free_text = data[['time','free_text', 'pcn', 'surgery']].copy()
do_better = data[['time','do_better', 'pcn', 'surgery']].copy()
campaign = data[['time', 'campaign_freetext', 'pcn', 'surgery', 'campaing_id']].copy()

In [10]:
free_text['origin'] = 'feedback'
do_better['origin'] = 'do_better'

In [13]:
free_text.head(2)

,time,free_text,pcn,surgery,origin
0,2024-01-01 10:51:00,Everyone kind and helpful,Brompton-Health-PCN,Scarsdale-Medical-Centre,feedback
1,2024-01-01 15:20:00,Nothing. It was all great,Brompton-Health-PCN,Brompton-Health-PCN,feedback

In [14]:
do_better.head(2)

,time,do_better,pcn,surgery,origin
0,2024-01-01 10:51:00,NaN,Brompton-Health-PCN,Scarsdale-Medical-Centre,do_better
1,2024-01-01 15:20:00,NaN,Brompton-Health-PCN,Brompton-Health-PCN,do_better

In [16]:
free_text.columns = ['time', 'review', 'pcn', 'surgery', 'origin']

In [18]:
do_better.columns = ['time', 'review', 'pcn', 'surgery', 'origin']

In [20]:
campaign.columns = ['time', 'review', 'pcn', 'surgery', 'origin']

In [27]:
free_text.dropna(inplace=True)
do_better.dropna(inplace=True)
campaign.dropna(inplace=True)

In [28]:
all_reviews = pd.concat([free_text, do_better, campaign], axis=0, ignore_index=False)

In [30]:
all_reviews.sample(50)

,time,review,pcn,surgery,origin
17032,2025-08-13 13:16:03,No,Brompton-Health-PCN,Kensington-Park-Medical-Centre,do_better
12341,2025-02-02 19:33:16,Digital screens check in was good. Appointment...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
11927,2025-01-21 13:41:59,The Reception area is two close to visitors as...,Brompton-Health-PCN,The-Chelsea-Practice,do_better
8384,2024-09-17 11:28:07,No,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better
13927,2025-04-04 11:45:44,I was invited to attend an open surgery for At...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
10130,2024-11-14 11:53:43,I was seen on time and kindly,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
9823,2024-10-31 11:25:26,All fine but getting the feedback in professio...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
9101,2024-10-10 17:06:30,Dr Kamvari and Pumphrey are always very helpful.,Brompton-Health-PCN,Kensington-Park-Medical-Centre,feedback
12615,2025-02-14 17:26:24,Very prompt and I got what I needed,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
9500,2024-10-22 18:19:36,"No, I couldn't expected a better experience.",Brompton-Health-PCN,Kensington-Park-Medical-Centre,do_better
4137,2024-04-17 17:41:39,Prompt response and appointment,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
5262,2024-05-28 17:05:14,No,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better
7248,2024-08-03 12:00:00,The front desk staff need totally changed,Brompton-Health-PCN,Earls-Court-Surgery,feedback
407,2024-02-14 11:04:55,have access to pediatricians at the surgery or...,Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better
12823,2025-02-27 17:15:02,Some speedier and clearer communication on wha...,Brompton-Health-PCN,Emperors-Gate-Health-Centre,do_better
6946,2024-07-27 13:03:34,Considering the fact that I've had so many pro...,Brompton-Health-PCN,Emperors-Gate-Health-Centre,feedback
5890,2024-06-20 20:12:49,I like how they TRY to help.,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
3633,2024-03-25 23:41:24,Not that I can think of.,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better
11145,2024-12-12 14:43:34,I like this gp the service is good,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
9356,2024-10-20 04:27:57,It was a flu jab appointment. It was on time a...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
15646,2025-06-23 13:26:01,"Laura, the nurse is very very capable and effi...",Brompton-Health-PCN,The-Chelsea-Practice,feedback
14010,2025-04-11 13:47:18,No. The visit was very good.,Brompton-Health-PCN,The-Chelsea-Practice,do_better
13718,2025-04-01 13:18:41,Appointment was a few minutes late,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better
9097,2024-10-10 14:29:48,Very good,Brompton-Health-PCN,Earls-Court-Surgery,flu_campaign_24
16930,2025-08-05 22:54:12,Everyone Ceru kind,Brompton-Health-PCN,Emperors-Gate-Health-Centre,feedback
8595,2024-09-24 13:11:14,No - I’m a happy patient,Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better
8357,2024-09-16 12:29:06,"No, everything went perfectly",Brompton-Health-PCN,Emperors-Gate-Health-Centre,do_better
18521,2025-10-10 17:37:03,Brilliant care from receptionists and the heal...,Brompton-Health-PCN,The-Chelsea-Practice,feedback
16173,2025-07-11 10:23:22,When I see the doctor I’m always treated well,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
5934,2024-06-21 12:38:17,No comments,Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better
1756,2024-02-29 13:36:58,Employ people who want to see patients. On the...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
8574,2024-09-24 11:26:09,"Very helpful, informative and friendly staff.",Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
14067,2025-04-12 19:14:39,"Respect to my sintoms and feelings,not rush,go...",Brompton-Health-PCN,Earls-Court-Medical-Centre,feedback
3309,2024-03-13 11:44:00,All Good,Brompton-Health-PCN,Scarsdale-Medical-Centre,feedback
5416,2024-06-04 15:12:00,Na,Brompton-Health-PCN,The-Chelsea-Practice,do_better
15546,2025-06-17 13:44:20,The process was very good,Brompton-Health-PCN,Kensington-Park-Medical-Centre,tel_access25
7371,2024-08-09 07:00:11,The staff are friendly and helpful and very qu...,Brompton-Health-PCN,Earls-Court-Medical-Centre,feedback
12794,2025-02-27 14:41:51,"the HCA to be dressed as a HCA , I never know ...",Brompton-Health-PCN,Earls-Court-Surgery,do_better
14826,2025-05-19 17:44:36,"No, more than happy with the service.",Brompton-Health-PCN,Kensington-Park-Medical-Centre,do_better
14846,2025-05-20 11:09:14,I was seen on time and my issue was well dealt...,Brompton-Health-PCN,The-Abingdon-Medical-Practice,feedback
15991,2025-07-03 13:52:09,"On time. Professional service, albeit for mino...",Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback
16174,2025-07-11 10:23:26,"Hi there,\nDr Hussein is always passion and I ...",Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
4608,2024-05-01 00:37:21,"Nothing, I would be hard pressed to find anoth...",Brompton-Health-PCN,Emperors-Gate-Health-Centre,do_better
3555,2024-03-22 18:02:12,The vaccination calendar for children is manag...,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
16950,2025-08-06 22:38:23,Background to the above: I have an ulcerated s...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better
4343,2024-04-23 20:05:53,Team members are helpful and caring!,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
15209,2025-06-01 20:22:08,No,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better
3965,2024-04-11 13:58:04,prefer face to face but understand not easy wi...,Brompton-Health-PCN,Earls-Court-Surgery,do_better
12159,2025-01-26 19:34:39,I trust Dc Standerline.,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback
16048,2025-07-04 13:02:41,No! It was more than I expected!,Brompton-Health-PCN,Earls-Court-Medical-Centre,do_better

In [31]:
all_reviews.shape

(26557, 5)

In [42]:
import numpy as np
def clean_data(df):
    # Copy the DataFrame to avoid modifying the original data
    cleaned_df = df.copy()
    # Apply the conditions and update the DataFrame
    cleaned_df.loc[cleaned_df["review_word_count"] < 4, "review"] = np.nan
    cleaned_df.dropna(inplace=True)
    return cleaned_df

In [43]:
def word_count(df):
    df["review_word_count"] = df["review"].apply(
        lambda x: len(str(x).split()) if isinstance(x, str) else np.nan)
    return df

In [44]:
all_reviews = word_count(all_reviews)

In [45]:
all_reviews = clean_data(all_reviews)

In [49]:
all_reviews.shape

(15610, 6)

In [51]:
all_reviews.sample(50)

,time,review,pcn,surgery,origin,review_word_count
4335,2024-04-23 19:47:50,"I like the staff, the nurses and most of the d...",Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback,11
2164,2024-02-29 19:10:18,This practice provides the best care I have ev...,Brompton-Health-PCN,Emperors-Gate-Health-Centre,feedback,32
2999,2024-03-07 08:38:05,Not used the website so can’t comment.,Brompton-Health-PCN,The-Good-Practice,feedback,7
17724,2025-09-11 12:08:35,They are just very good each time,Brompton-Health-PCN,Kensington-Park-Medical-Centre,feedback,7
15817,2025-06-30 15:27:34,Very good response time and quality,Brompton-Health-PCN,The-Chelsea-Practice,tel_access25,6
18132,2025-09-20 13:27:46,I got no definite answers that could help me,Brompton-Health-PCN,Kensington-Park-Medical-Centre,needs_met25,9
6209,2024-06-28 12:13:30,Simplified and consolidated IT . Do I use Patc...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better,16
9707,2024-10-29 09:59:27,Very good and was fortunate also as I had no c...,Brompton-Health-PCN,Stanhope-Mews-Surgery,flu_campaign_24,11
6563,2024-07-19 11:55:52,Whole experience was very positive from creati...,Brompton-Health-PCN,The-Abingdon-Medical-Practice,feedback,79
17384,2025-08-21 17:36:23,"Not for today, as everything runs smoothly thi...",Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better,9
6110,2024-06-27 13:15:45,"GP rushed me and send me out in 5 mins, tellin...",Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,18
8961,2024-10-03 12:30:04,The nurse was so cheerful and helpful and took...,Brompton-Health-PCN,Emperors-Gate-Health-Centre,feedback,28
12439,2025-02-06 09:00:05,I’m very happy with my surgery!! From the rece...,Brompton-Health-PCN,The-Abingdon-Medical-Practice,feedback,38
17488,2025-08-27 10:35:00,Your nurse is friendly and incredibly efficien...,Brompton-Health-PCN,Emperors-Gate-Health-Centre,feedback,15
12980,2025-03-04 11:12:21,"After speaking to Dr Ko on the telephone, she ...",Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback,39
3471,2024-03-20 09:50:00,I have had no issues with the current appointment,Brompton-Health-PCN,Scarsdale-Medical-Centre,feedback,9
13824,2025-04-03 14:19:20,"Just a little more continuity, I seem to meet ...",Brompton-Health-PCN,The-Chelsea-Practice,do_better,20
2327,2024-03-01 07:08:26,Yes hope the asthma check nurse and other te...,Brompton-Health-PCN,The-Chelsea-Practice,do_better,32
16872,2025-08-04 18:41:23,In the evening I was Number ELEVEN in the queu...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,tel_access25,24
17627,2025-09-02 12:34:16,I saw the doctor at the appointed hour and he ...,Brompton-Health-PCN,The-Abingdon-Medical-Practice,feedback,15
13226,2025-03-11 16:56:03,Receptionists are helpful and polite. Dr Sahi...,Brompton-Health-PCN,The-Abingdon-Medical-Practice,feedback,31
12370,2025-02-03 00:00:57,I have complex physical and mental health need...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,89
11890,2025-01-19 17:26:13,Request made by my cardiologist for a prescrip...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,47
2066,2024-02-29 16:58:00,I think that the doctors do care about us. On ...,Brompton-Health-PCN,The-Chelsea-Practice,feedback,49
2394,2024-03-01 13:01:47,I am very happy with the service I have receiv...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,22
7261,2024-08-03 12:00:00,Seeing face to face would have been better but...,Brompton-Health-PCN,Earls-Court-Surgery,do_better,15
13520,2025-03-21 18:38:39,It was the third time I had visited with suici...,Brompton-Health-PCN,The-Chelsea-Practice,feedback,120
503,2024-02-14 16:04:22,Doctors and Nurses and Staffs are so friendly ...,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback,17
4343,2024-04-23 20:05:53,Team members are helpful and caring!,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback,6
10053,2024-11-08 21:07:27,-receptionist are Very Helpful \n- The plebo...,Brompton-Health-PCN,Earls-Court-Medical-Centre,feedback,18
6995,2024-07-29 11:55:03,The receptionists should be more friendly and ...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better,8
16754,2025-07-31 10:39:43,The nurse was professional and friendly,Brompton-Health-PCN,The-Abingdon-Medical-Practice,feedback,6
13545,2025-03-23 21:12:30,Being able to book appointments after 5.15. I ...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better,17
4228,2024-04-22 11:09:44,The Surgery has always be accommodating and he...,Brompton-Health-PCN,Earls-Court-Surgery,feedback,22
13708,2025-04-01 12:57:43,Asked me in for an atrial fib test: done quick...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,12
14063,2025-04-12 13:44:39,Please specify in the app that request for med...,Brompton-Health-PCN,Earls-Court-Medical-Centre,nhs_app24,19
9359,2024-10-20 05:22:55,"Very well,the care professional explained what...",Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,flu_campaign_24,13
8750,2024-09-26 17:54:28,"Today I had an appointment for the flu job, at...",Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,72
5911,2024-06-21 08:32:42,The staff is friendly and efficient and seem t...,Brompton-Health-PCN,The-Chelsea-Practice,feedback,11
13330,2025-03-16 16:24:26,Unfortunately while my appointment was for 9.3...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better,14
15812,2025-06-30 13:08:25,Keep doing what you are doing . It seems to wo...,Brompton-Health-PCN,Kensington-Park-Medical-Centre,tel_access25,20
10756,2024-11-27 14:45:54,I think the doctor was very experienced and ve...,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback,16
6216,2024-06-29 06:42:53,Not to wait so long for appointment,Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better,7
9510,2024-10-23 18:01:02,Not feeling so rushed like before covid.,Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better,7
18015,2025-09-19 10:15:49,No. I was seen the same day and the nurse was ...,Brompton-Health-PCN,Stanhope-Mews-Surgery,do_better,12
522,2024-02-14 17:15:36,Yes making sure when I wait in line to be answ...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,do_better,25
8369,2024-09-17 10:42:28,Ida had problems with her ear and to extent th...,Brompton-Health-PCN,Health-Partners-at-Violet-Melchett,feedback,108
4751,2024-05-03 15:24:05,"The surgery is well-maintained and modern, but...",Brompton-Health-PCN,The-Chelsea-Practice,feedback,23
4608,2024-05-01 00:37:21,"Nothing, I would be hard pressed to find anoth...",Brompton-Health-PCN,Emperors-Gate-Health-Centre,do_better,14
3146,2024-03-08 12:25:20,Reception has improved and been more proactive...,Brompton-Health-PCN,Stanhope-Mews-Surgery,feedback,18